apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: product-catalog-service
spec:
  selector:
    matchLabels:
      app: product-catalog-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: product-catalog-service
          image: product-catalog-service:1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster