apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # The port that the container is running on in the cluster