apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort  # Change to LoadBalancer if using cloud provider