INSERT INTO product (name, description, price) VALUES ('Laptop', 'High-performance laptop', 1200.00);
INSERT INTO product (name, description, price) VALUES ('Smartphone', 'Latest smartphone model', 800.00);
INSERT INTO product (name, description, price) VALUES ('Tablet', 'Portable tablet for reading and browsing', 350.00);
INSERT INTO product (name, description, price) VALUES ('Headphones', 'Noise-cancelling headphones', 200.00);
INSERT INTO product (name, description, price) VALUES ('Keyboard', 'Ergonomic wireless keyboard', 80.00);
INSERT INTO product (name, description, price) VALUES ('Mouse', 'Wireless optical mouse', 30.00);
INSERT INTO product (name, description, price) VALUES ('Monitor', '27-inch 4K monitor', 450.00);
INSERT INTO product (name, description, price) VALUES ('Printer', 'Wireless inkjet printer', 150.00);
INSERT INTO product (name, description, price) VALUES ('External Hard Drive', '1TB external hard drive', 70.00);
INSERT INTO product (name, description, price) VALUES ('Webcam', 'High-definition webcam', 60.00);